var enterName = prompt("Iltimos ismingizni kiriting");
console.log("Siz kiritgan ism " + enterName);
var boolean = prompt("Biz sizga hozir misollar taqdim etamiz , Rozimisiz ha/yo'q");
console.log(boolean);
var firstEx = prompt("6 + 3 = ?");
console.log("6 + 3 = " + (6+3) + " , siz taqdim etgan javob " + firstEx );
var secondEx = prompt("10 * 91 = ?");
console.log("10 * 91 = " + (10*91) + " , siz taqdim etgan javob " + secondEx );
var thirdEx = prompt("10 % 90 = ?");
console.log("10 % 90 = " + (10%90) + " , siz taqdim etgan javob " + thirdEx );
var fourthEx = prompt("9 - 4 * 2 = ?");
console.log("9 - 4 * 2 = " + (9 - 4 * 3) + " , siz taqdim etgan javob " + fourthEx );
var fifthEx = prompt("10 * 2 + ( 20 / 10 ) = ?");
console.log("10 * 2 + ( 20 / 10 ) = " + (10 * 2 + ( 20 / 10 )) + " , siz taqdim etgan javob " + fifthEx );
var sixthEx = prompt("11 - 11 * 11 = ?");
console.log("11 - 11 * 11 = " + (11 - 11 * 11) + " , siz taqdim etgan javob " + sixthEx );
var seventhEx = prompt("0 - 2 + 4 = ?");
console.log("0 - 2 + 4 = " + (0 - 2 + 4) + " , siz taqdim etgan javob " + seventhEx );
var eightEx = prompt("1 - 9 % 90 = ?");
console.log("1 - 9 % 90 = " + (1 - 9 % 90) + " , siz taqdim etgan javob " + eightEx );